# Generated by Django 4.2.14 on 2024-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('grocery', 'Grocery'), ('food_delivery', 'Food Delivery'), ('online_order', 'Online Order'), ('sent_to_someone', 'Sent to Someone'), ('uber_rapido', 'Uber/Rapido'), ('shopping', 'Shopping'), ('others', 'Others')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
